name: check-code-with-pylint
on: [push]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version: 3.10.2
    - run: sudo apt-get install pylint
    - run: python lint_test.py
    - run: echo "Job status is ${{ job.status }}."
