name: import-code-to-image
on: [push]
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Repo checked out."
      - run: ls MihailAleksiev/devops-final-project
