name: Pipeline-PythonApp
on:
  push:
    branches:
      - branch-one
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - run: echo "Job status is ${{ job.status }}."
    - run: echo "${{secrets.PASSWORD}}"
  check-code-pylint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - run: |
        python -m pip install --upgrade pip
        pip install pylint
    - run: python lint_test.py
    - run: echo "Job status is ${{ job.status }}."
    - run: echo "${{secrets.PASSWORD}}"
  check-code-style:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
    - name: Style with pycodestyle
      run: |
        pycodestyle *.py
  simulate-build:
    needs: check-code-style
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
