name: Pipeline-PythonApp
on:
  push:
    branches:
      - branch-one
jobs:
  check-code-pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version: 3.10.2
    - run: |
        python -m pip install --upgrade pip
        pip install pylint
    - run: python lint_test.py
    - run: echo "Job status is ${{ job.status }}."
    - run: echo "${{secrets.PASSWORD}}"
